from __future__ import annotations

FILTER_AXIS_MAX_VALUES = 100
FILTER_AXIS_VALUE_MAX_LENGTH = 253
FILTER_LABEL_SELECTOR_MAX_VALUES = 24
FILTER_LABEL_VALUE_MAX_LENGTH = 1024
FILTER_SEARCH_MAX_LENGTH = 200
KUBERNETES_LABEL_NAME_MAX_LENGTH = 63
KUBERNETES_LABEL_PREFIX_MAX_LENGTH = 253
DEAD_LETTER_DEFAULT_LIMIT = 50
DEAD_LETTER_MAX_LIMIT = 100
RCA_QUERY_DEFAULT_LIMIT = 50
RCA_QUERY_MAX_LIMIT = 200
RCA_RECENT_CHANGE_DEFAULT_LIMIT = 5
