from __future__ import annotations

HEALTHZ_PATH = "/healthz"
READYZ_PATH = "/readyz"
AUTH_SESSION_PATH = "/auth/session"
AUTH_SESSION_REFRESH_PATH = "/auth/session/refresh"
AUTH_WORKSPACES_PATH = "/auth/workspaces"
AUTH_WORKSPACE_SWITCH_PATH = "/auth/workspaces/switch"
AUTH_LOGIN_PATH = "/auth/login"
AUTH_LOGOUT_PATH = "/auth/logout"
AUTH_APPROVE_USER_PATH = "/auth/users/{user_id}/approve"
GITHUB_WEBHOOK_PATH = "/github/webhook"
GITHUB_APP_CONFIG_PATH = "/integrations/github/app/config"
GITHUB_APP_INSTALL_URL_PATH = "/integrations/github/app/install-url"
GITHUB_APP_CALLBACK_PATH = "/integrations/github/app/callback"
GITHUB_APP_MANIFEST_PATH = "/integrations/github/app/manifest"
GITHUB_APP_MANIFEST_CALLBACK_PATH = "/integrations/github/app/manifest/callback"
GITHUB_APP_VERIFY_PATH = "/integrations/github/app/installations/{installation_id}/verify"
ALERTMANAGER_WEBHOOK_PATH = "/webhooks/alertmanager"
AGENT_CONNECT_PATH = "/agent/connect"
AGENT_EVIDENCE_PATH = "/agent/evidence"
INSTALL_MANIFEST_PATH = "/install/{agent_token}"
DEAD_LETTERS_PATH = "/dead-letters"
DEAD_LETTER_REPLAY_PATH = "/dead-letters/{dead_letter_id}/replay"
ORGS_PATH = "/orgs"
ORG_PATH = "/orgs/{org_id}"
GROUPS_PATH = "/groups"
GROUP_MEMBERS_PATH = "/groups/{group_id}/members"
GROUP_MEMBER_PATH = "/groups/{group_id}/members/{user_id}"
USERS_PATH = "/users"
ACCESS_PATH = "/access"
ACCESS_ITEM_PATH = "/access/{access_id}"
REPOSITORY_DISCOVERY_PROBE_PATH = "/repositories/discovery/probe"
REPOSITORY_DISCOVERY_BRANCHES_PATH = "/repositories/discovery/branches"
REPOSITORY_DISCOVERY_MANIFESTS_PATH = "/repositories/discovery/manifests"
REPOSITORY_DISCOVERY_VALIDATE_PATH = "/repositories/discovery/validate"
AGENT_EVIDENCE_JOB_SCHEDULE_PATH = "/agent/evidence/jobs"
AGENT_EVIDENCE_JOB_POLL_PATH = "/agent/evidence/jobs/poll"
AGENT_EVIDENCE_JOB_RESULT_PATH = "/agent/evidence/jobs/{job_id}/result"
EVIDENCE_QUERY_PATH = "/evidence"
EVIDENCE_WINDOWS_PATH = "/evidence/windows"
EVIDENCE_WINDOW_PATH = "/evidence/windows/{evidence_key}"
RCA_REPORTS_PATH = "/rca-reports"
RCA_RULES_PATH = "/rca/rules"
RCA_RULES_VALIDATE_PATH = "/rca/rules/validate"
RCA_BUNDLE_PATH = "/rca/bundles/{correlation_id}"
RCA_RECOVERY_PLAN_BY_CORRELATION_PATH = "/rca/recovery-plans/by-correlation/{correlation_id}"
RCA_RECOVERY_ACTION_SELECT_BY_CORRELATION_PATH = (
    "/rca/recovery-plans/by-correlation/{correlation_id}/actions/select"
)
RCA_RECOVERY_ACTION_SELECT_PATH = "/rca/recovery-plans/{plan_id}/actions/{action_id}/select"
RCA_RECOVERY_RETRY_BY_CORRELATION_PATH = "/rca/recovery-plans/by-correlation/{correlation_id}/retry"


def agent_evidence_job_result_path(job_id: str) -> str:
    return AGENT_EVIDENCE_JOB_RESULT_PATH.format(job_id=job_id)
